### ISSUE TITLE
Authors can only have multiple affiliations

### ISSUE THREAD

**Issue by ArnoutDevos** [rescience-c/template#8]
When one of the authors has a single affiliation, the following error is encountered:

```
make draft  
                                                                              
./yaml-to-latex.py -i metadata-draft.yaml -o metadata-draft.tex
Traceback (most recent call last):
  File "./yaml-to-latex.py", line 84, in <module>
    article = Article(file.read())
  File "/Users/devos/Documents/phd/research/iclr2019/template/article.py", line 135, in __init__
    self.parse(data)
  File "/Users/devos/Documents/phd/research/iclr2019/template/article.py", line 194, in parse
    affiliations = item["affiliations"].split(",")
AttributeError: 'int' object has no attribute 'split'
make: *** [metadata-draft.tex] Error 1
```

**Comment by ArnoutDevos** [comment]
Fixed in https://github.com/rescience-c/template/pull/9
